#!/bin/bash

readonly rules_dir='/rules/firestore'
readonly header_file='header.rules'
readonly footer_file='footer.rules'
readonly route_file='routes.rules'
readonly helper_file='helper.rules'
readonly funcs_dir='/functions'
readonly in_files=(
  'getAccount.rules'
  'getCollectionProduct.rules'
  'getGalleryPostCreate.rules'
  'getGalleryPostDelete.rules'
)
readonly out_file='firestore.rules'

print_source_files() {
  echo $route_file
  for file in ${in_files[@]}; do
    echo $file
  done
  echo $helper_file
}

main() {
  readonly work_file='firestore.rules.work'
  touch $work_file

  cat ".${rules_dir}/${header_file}" >> $work_file

  cat ".${rules_dir}/${route_file}" | sed -e '/^$/d' | sed 's/^/    /g' >> $work_file
  echo >> $work_file

  for file in ${in_files[@]}; do
    echo "    // ${file} //" >> $work_file
    cat ".${rules_dir}${funcs_dir}/${file}" | sed -e '/^$/d' | sed 's/^/    /g' >> $work_file
    echo >> $work_file
  done

  echo "    // ${helper_file} //" >> $work_file
  cat ".${rules_dir}/${helper_file}" | sed -e '/^$/d' | sed 's/^/    /g' >> $work_file

  cat ".${rules_dir}/${footer_file}" >> $work_file

  cat $work_file > $out_file
  rm $work_file
}

print_source_files
main
